/* =============================================
   LEGAL-LANG.JS — POP-E i18n pour pages légales
   ============================================= */

const LEGAL_TRANSLATIONS = {
  fr: {
    /* ── Nav ── */
    nav_back: '← Retour',

    /* ── Mentions légales ── */
    ml_badge:         'DOCUMENT OFFICIEL',
    ml_title:         'MENTIONS<br><span>LÉGALES</span>',
    ml_meta_company:  'POP-E SAS',
    ml_meta_date:     'Dernière mise à jour : Juin 2026',
    ml_meta_version:  'Version 1.0',

    ml_toc_title:     'SOMMAIRE',
    ml_toc_1:         'Éditeur du site',
    ml_toc_2:         'Hébergeur',
    ml_toc_3:         'Propriété intellectuelle',
    ml_toc_4:         'Limitation de responsabilité',
    ml_toc_5:         'Données personnelles',
    ml_toc_6:         'Cookies',
    ml_toc_7:         'Droit applicable',
    ml_toc_8:         'Contact',

    ml_s1_num:        '01',
    ml_s1_title:      'ÉDITEUR DU SITE',
    ml_s1_p1:         'Le site <strong>pop-e.fr</strong> est édité par la société <strong>POP-E SAS</strong>, société par actions simplifiée au capital de 1000 €, immatriculée au Registre du Commerce et des Sociétés compétent sous le numéro <strong>944 684 778</strong>, 180 B chemin de Saint Andre 13760 Saint-Cannat',
    ml_s1_highlight:  'Ce site a été conçu et développé par <strong>Sinda Amara</strong> et <strong>Thomas Palot</strong>, étudiants en 2ème année de BUT Informatique, dans le cadre de leur stage chez POP-E.',
    ml_s1_siege:      'Siège social',
    ml_s1_siege_val:  '180 B CHEMIN DE SAINT ANDRE 13760 SAINT-CANNAT',
    ml_s1_siret:      'SIRET',
    ml_s1_siret_val:  '944 684 778 00001',
    ml_s1_tva:        'TVA intra.',
    ml_s1_tva_val:    'FR11 944 684 778',
    ml_s1_dir:        'Directeur pub.',
    ml_s1_dir_val:    'Andréa Tatikian',
    ml_s1_dev:        'Développeurs',
    ml_s1_dev_val:    'Sinda Amara et Thomas Palot — stagiaires BUT Informatique 2ème année',
    ml_s1_email:      'Email',

    ml_s2_num:        '02',
    ml_s2_title:      'HÉBERGEUR',
    ml_s2_p1:         'Le site est hébergé par :',
    ml_s2_soc:        'Société',
    ml_s2_soc_val:    '[Nom de l\'hébergeur]',
    ml_s2_addr:       'Adresse',
    ml_s2_addr_val:   '[Adresse de l\'hébergeur]',
    ml_s2_site:       'Site web',
    ml_s2_site_val:   '[Site de l\'hébergeur]',

    ml_s3_num:        '03',
    ml_s3_title:      'PROPRIÉTÉ INTELLECTUELLE',
    ml_s3_p1:         'L\'ensemble des éléments constituant ce site (textes, graphismes, logiciels, photographies, images, sons, plans, logos, marques, etc.) est la propriété exclusive de <strong>POP-E SAS</strong> ou de ses partenaires.',
    ml_s3_p2:         'Toute reproduction, représentation, modification, publication, adaptation ou exploitation de tout ou partie des éléments du site, quel que soit le moyen ou le procédé utilisé, est interdite sans l\'autorisation écrite préalable de POP-E SAS.',
    ml_s3_highlight:  'La marque <strong>POP-E</strong>, le logo et les signes distinctifs associés sont des marques déposées. Toute utilisation non autorisée constitue une contrefaçon passible de sanctions.',

    ml_s4_num:        '04',
    ml_s4_title:      'LIMITATION DE RESPONSABILITÉ',
    ml_s4_p1:         'POP-E SAS s\'efforce d\'assurer l\'exactitude et la mise à jour des informations diffusées sur ce site. Toutefois, POP-E SAS ne peut garantir l\'exactitude, la précision ou l\'exhaustivité des informations mises à disposition.',
    ml_s4_p2:         'POP-E SAS décline toute responsabilité pour :',
    ml_s4_li1:        'Toute imprécision, inexactitude ou omission portant sur des informations disponibles sur le site',
    ml_s4_li2:        'Tous dommages résultant d\'une intrusion frauduleuse d\'un tiers ayant entraîné une modification des informations',
    ml_s4_li3:        'Tout dommage subi par l\'utilisateur en raison d\'une interruption ou indisponibilité du service',
    ml_s4_li4:        'Tout dommage causé par des liens hypertextes et au contenu des sites internet vers lesquels ces liens pointent',

    ml_s5_num:        '05',
    ml_s5_title:      'DONNÉES PERSONNELLES',
    ml_s5_p1:         'Le traitement des données personnelles collectées via ce site est régi par notre <a href="/legal/confidentialite.html">Politique de Confidentialité</a>, conformément au Règlement Général sur la Protection des Données (RGPD — UE 2016/679).',
    ml_s5_p2:         'Vous disposez d\'un droit d\'accès, de rectification, d\'effacement et de portabilité de vos données. Pour exercer ces droits, consultez la page <a href="/legal/confidentialite.html">Politique de Confidentialité</a> ou contactez-nous à <a href="mailto:contact@pop-e.eu">contact@pop-e.eu</a>.',

    ml_s6_num:        '06',
    ml_s6_title:      'COOKIES',
    ml_s6_p1:         'À ce jour, le site pop-e.fr n\'utilise pas de cookies ou traceurs non essentiels nécessitant le consentement préalable des visiteurs. Seuls des traceurs strictement nécessaires au bon fonctionnement technique du site peuvent être utilisés, le cas échéant, afin d\'assurer l\'affichage des pages, la sécurité du site ou la navigation. Si des cookies de mesure d\'audience, de publicité ou de suivi venaient à être ajoutés ultérieurement, un bandeau de consentement conforme à la réglementation applicable serait mis en place.',

    ml_s7_num:        '07',
    ml_s7_title:      'DROIT APPLICABLE',
    ml_s7_p1:         'Les présentes mentions légales sont soumises au droit français. En cas de litige et à défaut de résolution amiable, les tribunaux français seront seuls compétents.',
    ml_s7_p2:         'Conformément à l\'article L.612-1 du Code de la consommation, tout consommateur a le droit de recourir gratuitement à un médiateur de la consommation en vue de la résolution amiable du litige qui l\'oppose à un professionnel.',

    ml_s8_num:        '08',
    ml_s8_title:      'CONTACT',
    ml_s8_p1:         'Pour toute question relative aux présentes mentions légales, vous pouvez nous contacter :',
    ml_s8_email:      'Email',
    ml_s8_courrier:   'Courrier',
    ml_s8_courrier_val: 'POP-E SAS — 180 B chemin de Saint-André 13760 Saint-Cannat, France',

    /* ── CGU ── */
    cgu_badge:        'CONDITIONS D\'UTILISATION',
    cgu_title:        'CONDITIONS<br><span>GÉNÉRALES</span><br>D\'UTILISATION',
    cgu_meta_date:    'En vigueur au 1er Juin 2026',
    cgu_meta_version: 'Version 1.0',

    cgu_toc_title:    'SOMMAIRE',
    cgu_toc_1:        'Objet et champ d\'application',
    cgu_toc_2:        'Description du service',
    cgu_toc_3:        'Inscription et compte utilisateur',
    cgu_toc_4:        'Conditions d\'utilisation',
    cgu_toc_5:        'Tarifs et paiement',
    cgu_toc_6:        'Responsabilités',
    cgu_toc_7:        'Suspension et résiliation',
    cgu_toc_8:        'Données personnelles',
    cgu_toc_9:        'Modifications des CGU',
    cgu_toc_10:       'Litiges',
    cgu_toc_11:       'Nous contacter',

    cgu_s1_num:       '01',
    cgu_s1_title:     'OBJET ET CHAMP D\'APPLICATION',
    cgu_s1_p1:        'Les présentes Conditions Générales d\'Utilisation (CGU) régissent l\'accès et l\'utilisation du service POP-E proposé par la société <strong>POP-E SAS</strong>, ainsi que de l\'application mobile et du site web associés.',
    cgu_s1_p2:        'En accédant au service, vous acceptez sans réserve l\'ensemble des présentes CGU. Si vous n\'acceptez pas ces conditions, vous ne devez pas utiliser le service POP-E.',
    cgu_s1_highlight: 'Ces CGU s\'appliquent à tout utilisateur ayant créé un compte POP-E ou ayant utilisé une borne de location de batterie externe POP-E.',

    cgu_s2_num:       '02',
    cgu_s2_title:     'DESCRIPTION DU SERVICE',
    cgu_s2_p1:        'POP-E propose un service de <strong>location de batteries externes en libre-service</strong> accessible via des bornes installées dans des lieux partenaires (festivals, centres commerciaux, transports, etc.).',
    cgu_s2_p2:        'Le service comprend :',
    cgu_s2_li1:       'La mise à disposition de batteries externes portables via des bornes connectées',
    cgu_s2_li2:       'Une application mobile permettant de localiser les bornes, de gérer la location et le paiement',
    cgu_s2_li3:       'Un système de retour flexible dans n\'importe quelle borne du réseau POP-E',
    cgu_s2_li4:       'Un suivi en temps réel de la location et de la facturation',
    cgu_s2_p3:        'POP-E se réserve le droit de modifier ou d\'interrompre tout ou partie du service à tout moment, avec ou sans préavis.',

    cgu_s3_num:       '03',
    cgu_s3_title:     'INSCRIPTION ET COMPTE UTILISATEUR',
    cgu_s3_p1:        'L\'utilisation du service POP-E nécessite la création d\'un compte utilisateur. Vous vous engagez à :',
    cgu_s3_li1:       'Fournir des informations exactes, complètes et à jour lors de l\'inscription',
    cgu_s3_li2:       'Maintenir la confidentialité de vos identifiants de connexion',
    cgu_s3_li3:       'Être l\'unique responsable de toutes les actions effectuées depuis votre compte',
    cgu_s3_li4:       'Notifier immédiatement POP-E de toute utilisation non autorisée de votre compte',
    cgu_s3_p2:        'Le service est réservé aux personnes physiques majeures (18 ans et plus) ou aux mineurs avec autorisation parentale explicite. POP-E se réserve le droit de refuser l\'inscription ou de suspendre un compte sans justification.',

    cgu_s4_num:       '04',
    cgu_s4_title:     'CONDITIONS D\'UTILISATION',
    cgu_s4_p1:        'En utilisant le service POP-E, vous vous engagez à :',
    cgu_s4_li1:       'Utiliser les batteries uniquement pour recharger des appareils électroniques personnels',
    cgu_s4_li2:       'Restituer la batterie dans une borne POP-E du réseau dans un délai maximum de <strong>72 heures</strong>',
    cgu_s4_li3:       'Manipuler les batteries avec soin et ne pas les endommager volontairement',
    cgu_s4_li4:       'Ne pas tenter de démonter, modifier ou altérer les batteries ou les bornes',
    cgu_s4_li5:       'Ne pas utiliser le service à des fins illicites ou contraires à l\'ordre public',
    cgu_s4_highlight: 'En cas de perte ou de non-retour d\'une batterie au-delà de 72h, des frais de <strong>remplacement forfaitaires</strong> seront facturés automatiquement sur votre moyen de paiement enregistré.',

    cgu_s5_num:       '05',
    cgu_s5_title:     'TARIFS ET PAIEMENT',
    cgu_s5_p1:        'Les tarifs en vigueur sont affichés dans l\'application POP-E et sur les bornes avant toute location. La facturation s\'effectue à la durée réelle de location, à partir du retrait de la batterie jusqu\'à son retour dans une borne.',
    cgu_s5_th1:       'Durée',
    cgu_s5_th2:       'Tarif',
    cgu_s5_th3:       'Remarque',
    cgu_s5_r1c1:      'Jusqu\'à 30 min',
    cgu_s5_r1c2:      'Gratuit',
    cgu_s5_r1c3:      'Sous réserve de disponibilité',
    cgu_s5_r2c1:      '30 min — 4h',
    cgu_s5_r2c2:      'À partir de 1,50 €',
    cgu_s5_r2c3:      'Tarif par tranche de 30 min',
    cgu_s5_r3c1:      '4h — 24h',
    cgu_s5_r3c2:      'À partir de 5 €',
    cgu_s5_r3c3:      'Tarif journalier',
    cgu_s5_r4c1:      'Au-delà de 72h',
    cgu_s5_r4c2:      'Frais de remplacement',
    cgu_s5_r4c3:      'Tarif affiché en application',
    cgu_s5_p2:        'Le paiement s\'effectue exclusivement par carte bancaire ou via les solutions de paiement intégrées à l\'application (Apple Pay, Google Pay). Aucun paiement en espèces n\'est accepté.',

    cgu_s6_num:       '06',
    cgu_s6_title:     'RESPONSABILITÉS',
    cgu_s6_p1:        'POP-E s\'engage à mettre en œuvre tous les moyens raisonnables pour assurer la disponibilité et le bon fonctionnement du service. Cependant, POP-E ne saurait être tenu responsable :',
    cgu_s6_li1:       'Des dommages causés à vos appareils par l\'utilisation des batteries',
    cgu_s6_li2:       'Des interruptions de service dues à des maintenances ou pannes techniques',
    cgu_s6_li3:       'Des actes de vandalisme ou de vol sur les bornes hors de son contrôle',
    cgu_s6_li4:       'Des pertes de données ou d\'informations stockées sur vos appareils',
    cgu_s6_p2:        'En tant qu\'utilisateur, vous êtes entièrement responsable de l\'utilisation que vous faites du service et des conséquences qui en découlent.',

    cgu_s7_num:       '07',
    cgu_s7_title:     'SUSPENSION ET RÉSILIATION',
    cgu_s7_p1:        'POP-E se réserve le droit de suspendre ou résilier votre compte en cas de :',
    cgu_s7_li1:       'Non-respect des présentes CGU',
    cgu_s7_li2:       'Comportement frauduleux ou tentative de fraude',
    cgu_s7_li3:       'Non-paiement des sommes dues',
    cgu_s7_li4:       'Non-retour de matériel après mise en demeure',
    cgu_s7_p2:        'Vous pouvez à tout moment demander la suppression de votre compte en contactant notre service client ou via les paramètres de l\'application.',

    cgu_s8_num:       '08',
    cgu_s8_title:     'DONNÉES PERSONNELLES',
    cgu_s8_p1:        'POP-E collecte et traite vos données personnelles dans le cadre de la fourniture du service, conformément au RGPD. Pour plus d\'informations, consultez notre <a href="/legal/confidentialite.html">Politique de Confidentialité</a>.',

    cgu_s9_num:       '09',
    cgu_s9_title:     'MODIFICATIONS DES CGU',
    cgu_s9_p1:        'POP-E se réserve le droit de modifier les présentes CGU à tout moment. Les modifications entrent en vigueur dès leur publication sur le site et l\'application. En cas de modification substantielle, vous serez notifié par email au moins 15 jours avant l\'entrée en vigueur.',
    cgu_s9_p2:        'L\'utilisation continue du service après notification vaut acceptation des nouvelles conditions.',

    cgu_s10_num:      '10',
    cgu_s10_title:    'LITIGES',
    cgu_s10_p1:       'En cas de litige, vous pouvez contacter notre service client pour une résolution amiable. À défaut d\'accord, vous pouvez recourir gratuitement à un médiateur de la consommation.',
    cgu_s10_p2:       'Les présentes CGU sont soumises au droit français. À défaut de résolution amiable, les tribunaux compétents de Paris seront saisis.',

    cgu_s11_num:      '11',
    cgu_s11_title:    'NOUS CONTACTER',
    cgu_s11_p1:       'Pour toute question relative aux présentes CGU, une réclamation ou une demande de résiliation, contactez-nous via le formulaire ci-dessous.',
    cgu_form_fname:   'Prénom *',
    cgu_form_lname:   'Nom *',
    cgu_form_email:   'Email *',
    cgu_form_phone:   'Téléphone (optionnel)',
    cgu_form_subject: 'Sujet de votre demande *',
    cgu_form_opt1:    'Question sur les CGU',
    cgu_form_opt2:    'Réclamation',
    cgu_form_opt3:    'Résiliation de compte',
    cgu_form_opt4:    'Litige paiement',
    cgu_form_opt5:    'Autre',
    cgu_form_msg:     'Votre message *',
    cgu_form_submit:  'ENVOYER MON MESSAGE →',
    cgu_form_sending: 'ENVOI EN COURS...',
    cgu_form_error:   'ERREUR — RÉESSAYER',
    cgu_form_success: '✓ Votre message a bien été envoyé. Nous vous répondrons sous 48h.',

    /* ── Confidentialité ── */
    conf_badge:       'RGPD — UE 2016/679',
    conf_title:       'POLITIQUE DE<br><span>CONFIDENTIALITÉ</span>',
    conf_meta_date:   'Mise à jour : Juin 2026',
    conf_meta_rgpd:   'Conforme RGPD',

    conf_toc_title:   'SOMMAIRE',
    conf_toc_1:       'Responsable du traitement',
    conf_toc_2:       'Données collectées',
    conf_toc_3:       'Finalités et bases légales',
    conf_toc_4:       'Durées de conservation',
    conf_toc_5:       'Partage des données',
    conf_toc_6:       'Transferts hors UE',
    conf_toc_7:       'Sécurité',
    conf_toc_8:       'Vos droits',
    conf_toc_9:       'Cookies',
    conf_toc_10:      'Exercer vos droits',

    conf_intro:       'POP-E s\'engage à protéger votre vie privée. Cette politique explique quelles données nous collectons, pourquoi, comment nous les utilisons et quels sont vos droits. Nous ne vendons jamais vos données personnelles à des tiers.',

    conf_s1_num:      '01',
    conf_s1_title:    'RESPONSABLE DU TRAITEMENT',
    conf_s1_p1:       'Le responsable du traitement de vos données personnelles est :',
    conf_s1_soc:      'Société',
    conf_s1_addr:     'Adresse',
    conf_s1_addr_val: '180 B CHEMIN DE SAINT ANDRE, 13760 Saint-Cannat, France',
    conf_s1_dpo:      'DPO / Contact',

    conf_s2_num:      '02',
    conf_s2_title:    'DONNÉES COLLECTÉES',
    conf_s2_p1:       'Nous collectons les catégories de données suivantes selon votre utilisation du service :',
    conf_s2_th1:      'Catégorie',
    conf_s2_th2:      'Données collectées',
    conf_s2_th3:      'Source',
    conf_s2_r1c1:     'Identité',
    conf_s2_r1c2:     'Nom, prénom, date de naissance',
    conf_s2_r1c3:     'Inscription directe',
    conf_s2_r2c1:     'Contact',
    conf_s2_r2c2:     'Adresse email, numéro de téléphone',
    conf_s2_r2c3:     'Inscription directe',
    conf_s2_r3c1:     'Paiement',
    conf_s2_r3c2:     'Données bancaires tokenisées (via prestataire PSP)',
    conf_s2_r3c3:     'Lors du paiement',
    conf_s2_r4c1:     'Localisation',
    conf_s2_r4c2:     'Position GPS (uniquement si autorisée)',
    conf_s2_r4c3:     'Application mobile',
    conf_s2_r5c1:     'Usage',
    conf_s2_r5c2:     'Historique de locations, bornes utilisées, durées',
    conf_s2_r5c3:     'Utilisation du service',
    conf_s2_r6c1:     'Technique',
    conf_s2_r6c2:     'Adresse IP, type d\'appareil, système d\'exploitation',
    conf_s2_r6c3:     'Navigation automatique',
    conf_s2_p2:       'Nous ne collectons pas de données sensibles au sens de l\'article 9 du RGPD (origine ethnique, données de santé, opinions politiques, etc.).',

    conf_s3_num:      '03',
    conf_s3_title:    'FINALITÉS ET BASES LÉGALES',
    conf_s3_th1:      'Finalité',
    conf_s3_th2:      'Base légale',
    conf_s3_r1c1:     'Gestion du compte et fourniture du service',
    conf_s3_r1c2:     'Exécution du contrat',
    conf_s3_r2c1:     'Facturation et gestion des paiements',
    conf_s3_r2c2:     'Exécution du contrat / Obligation légale',
    conf_s3_r3c1:     'Envoi de notifications relatives à votre location',
    conf_s3_r3c2:     'Exécution du contrat',
    conf_s3_r4c1:     'Communication commerciale et offres POP-E',
    conf_s3_r4c2:     'Consentement (opt-in)',
    conf_s3_r5c1:     'Amélioration du service et analyse d\'audience',
    conf_s3_r5c2:     'Intérêt légitime',
    conf_s3_r6c1:     'Prévention de la fraude et sécurité',
    conf_s3_r6c2:     'Intérêt légitime / Obligation légale',
    conf_s3_r7c1:     'Respect des obligations légales et comptables',
    conf_s3_r7c2:     'Obligation légale',

    conf_s4_num:      '04',
    conf_s4_title:    'DURÉES DE CONSERVATION',
    conf_s4_li1:      '<strong>Données de compte actif</strong> — conservées pendant toute la durée de la relation contractuelle',
    conf_s4_li2:      '<strong>Données de transaction</strong> — 10 ans (obligation comptable)',
    conf_s4_li3:      '<strong>Historique de location</strong> — 3 ans après la dernière utilisation',
    conf_s4_li4:      '<strong>Données de connexion / logs</strong> — 12 mois',
    conf_s4_li5:      '<strong>Données de localisation</strong> — 90 jours',
    conf_s4_li6:      '<strong>Données marketing (si consentement)</strong> — jusqu\'au retrait du consentement ou 3 ans d\'inactivité',
    conf_s4_p1:       'Après expiration de ces délais, vos données sont soit supprimées, soit anonymisées de façon irréversible à des fins statistiques.',

    conf_s5_num:      '05',
    conf_s5_title:    'PARTAGE DES DONNÉES',
    conf_s5_p1:       'Vos données peuvent être partagées avec les catégories de destinataires suivants, dans le strict cadre des finalités décrites :',
    conf_s5_li1:      '<strong>Prestataires de paiement</strong> — pour le traitement sécurisé des transactions (ex. Stripe, Mangopay)',
    conf_s5_li2:      '<strong>Hébergeurs et prestataires techniques</strong> — dans le cadre de l\'exploitation du service',
    conf_s5_li3:      '<strong>Prestataires d\'analyse</strong> — pour l\'amélioration du service (données anonymisées ou sous contrat de sous-traitance RGPD)',
    conf_s5_li4:      '<strong>Autorités compétentes</strong> — uniquement sur réquisition judiciaire ou légale',
    conf_s5_highlight: '<strong>Nous ne vendons jamais vos données personnelles</strong> à des tiers à des fins commerciales.',

    conf_s6_num:      '06',
    conf_s6_title:    'TRANSFERTS HORS UE',
    conf_s6_p1:       'Certains de nos prestataires techniques peuvent être établis en dehors de l\'Union Européenne. Dans ce cas, nous nous assurons que les transferts de données sont encadrés par des garanties appropriées :',
    conf_s6_li1:      'Décision d\'adéquation de la Commission européenne',
    conf_s6_li2:      'Clauses contractuelles types (CCT) approuvées par la Commission européenne',
    conf_s6_li3:      'Certification du prestataire sous un mécanisme reconnu (ex. EU-US Data Privacy Framework)',

    conf_s7_num:      '07',
    conf_s7_title:    'SÉCURITÉ',
    conf_s7_p1:       'POP-E met en œuvre des mesures techniques et organisationnelles appropriées pour protéger vos données contre tout accès non autorisé, divulgation, altération ou destruction :',
    conf_s7_li1:      'Chiffrement des données en transit (TLS 1.3) et au repos (AES-256)',
    conf_s7_li2:      'Accès aux données limité aux seuls personnels habilités',
    conf_s7_li3:      'Authentification à deux facteurs pour les accès administrateurs',
    conf_s7_li4:      'Audits de sécurité réguliers',
    conf_s7_li5:      'Procédure de notification des violations de données dans les 72h (RGPD art. 33)',

    conf_s8_num:      '08',
    conf_s8_title:    'VOS DROITS',
    conf_s8_p1:       'Conformément au RGPD, vous disposez des droits suivants sur vos données personnelles :',
    conf_s8_th1:      'Droit',
    conf_s8_th2:      'Description',
    conf_s8_r1c1:     'Accès',
    conf_s8_r1c2:     'Obtenir une copie de toutes vos données personnelles que nous traitons',
    conf_s8_r2c1:     'Rectification',
    conf_s8_r2c2:     'Corriger des données inexactes ou incomplètes vous concernant',
    conf_s8_r3c1:     'Effacement',
    conf_s8_r3c2:     'Demander la suppression de vos données (sous réserve d\'obligations légales)',
    conf_s8_r4c1:     'Limitation',
    conf_s8_r4c2:     'Restreindre le traitement de vos données dans certaines circonstances',
    conf_s8_r5c1:     'Portabilité',
    conf_s8_r5c2:     'Recevoir vos données dans un format structuré et lisible par machine',
    conf_s8_r6c1:     'Opposition',
    conf_s8_r6c2:     'Vous opposer au traitement fondé sur l\'intérêt légitime ou à des fins marketing',
    conf_s8_r7c1:     'Retrait du consentement',
    conf_s8_r7c2:     'Retirer à tout moment votre consentement sans que cela affecte les traitements antérieurs',
    conf_s8_p2:       'Vous avez également le droit d\'introduire une réclamation auprès de la <strong>CNIL</strong> (Commission Nationale de l\'Informatique et des Libertés) : <a href="https://www.cnil.fr" target="_blank" rel="noopener">www.cnil.fr</a>',

    conf_s9_num:      '09',
    conf_s9_title:    'COOKIES',
    conf_s9_p1:       'Notre site utilise des cookies et technologies similaires. Vous pouvez gérer vos préférences à tout moment via notre bandeau de consentement ou les paramètres de votre navigateur.',
    conf_s9_th1:      'Type',
    conf_s9_th2:      'Finalité',
    conf_s9_th3:      'Durée',
    conf_s9_th4:      'Consentement',
    conf_s9_r1c1:     'Essentiels',
    conf_s9_r1c2:     'Fonctionnement du site, session, langue',
    conf_s9_r1c3:     'Session',
    conf_s9_r1c4:     'Non requis',
    conf_s9_r2c1:     'Analytiques',
    conf_s9_r2c2:     'Mesure d\'audience anonymisée',
    conf_s9_r2c3:     '13 mois',
    conf_s9_r2c4:     'Requis',
    conf_s9_r3c1:     'Fonctionnels',
    conf_s9_r3c2:     'Mémorisation préférences utilisateur',
    conf_s9_r3c3:     '12 mois',
    conf_s9_r3c4:     'Requis',
    conf_s9_r4c1:     'Marketing',
    conf_s9_r4c2:     'Publicités personnalisées (si activé)',
    conf_s9_r4c3:     '6 mois',
    conf_s9_r4c4:     'Requis',

    conf_s10_num:     '10',
    conf_s10_title:   'EXERCER VOS DROITS',
    conf_s10_p1:      'Pour exercer l\'un de vos droits, remplissez le formulaire ci-dessous. Nous nous engageons à vous répondre dans un délai d\'<strong>un mois</strong> à compter de la réception de votre demande (RGPD art. 12).',
    conf_s10_p2:      'Une pièce d\'identité pourra vous être demandée pour vérifier votre identité avant traitement.',
    conf_form_fname:  'Prénom *',
    conf_form_lname:  'Nom *',
    conf_form_email:  'Email associé à votre compte POP-E *',
    conf_form_phone:  'Téléphone (optionnel)',
    conf_form_right:  'Droit que vous souhaitez exercer *',
    conf_form_opt1:   'Droit d\'accès — obtenir mes données',
    conf_form_opt2:   'Droit de rectification — corriger mes données',
    conf_form_opt3:   'Droit à l\'effacement — supprimer mes données',
    conf_form_opt4:   'Droit à la limitation du traitement',
    conf_form_opt5:   'Droit à la portabilité',
    conf_form_opt6:   'Droit d\'opposition',
    conf_form_opt7:   'Retrait du consentement marketing',
    conf_form_opt8:   'Autre demande',
    conf_form_detail: 'Précisez votre demande (optionnel)',
    conf_form_submit: 'SOUMETTRE MA DEMANDE →',
    conf_form_sending:'ENVOI EN COURS...',
    conf_form_error:  'ERREUR — RÉESSAYER',
    conf_form_success:'✓ Votre demande a bien été reçue. Nous vous répondrons dans un délai maximum d\'un mois.',

    /* ── Footer commun ── */
    footer_tagline:   'La batterie externe en libre-service.<br>Partout. Tout le temps.',
    footer_col1:      'Solution',
    footer_how:       'Comment ça marche',
    footer_where:     'Où utiliser POP-E',
    footer_amb:       'Ambassadeur',
    footer_col2:      'Entreprise',
    footer_about:     'À propos',
    footer_impact:    'Impact',
    footer_press:     'Presse',
    footer_col3:      'Contact',
    footer_contact:   'Nous contacter',
    footer_install:   'Installer une borne',
    footer_support:   'Support',
    footer_rights:    '© 2026 POP-E. Tous droits réservés.',
    footer_legal1:    'Mentions légales',
    footer_cgu:       'CGU',
    footer_privacy:   'Confidentialité',
  },

  en: {
    /* ── Nav ── */
    nav_back: '← Back',

    /* ── Legal notice ── */
    ml_badge:         'OFFICIAL DOCUMENT',
    ml_title:         'LEGAL<br><span>NOTICE</span>',
    ml_meta_company:  'POP-E SAS',
    ml_meta_date:     'Last updated: June 2026',
    ml_meta_version:  'Version 1.0',

    ml_toc_title:     'CONTENTS',
    ml_toc_1:         'Publisher',
    ml_toc_2:         'Hosting',
    ml_toc_3:         'Intellectual property',
    ml_toc_4:         'Limitation of liability',
    ml_toc_5:         'Personal data',
    ml_toc_6:         'Cookies',
    ml_toc_7:         'Applicable law',
    ml_toc_8:         'Contact',

    ml_s1_num:        '01',
    ml_s1_title:      'PUBLISHER',
    ml_s1_p1:         'The website <strong>pop-e.fr</strong> is published by <strong>POP-E SAS</strong>, a simplified joint-stock company with share capital of €1,000, registered in the relevant Trade and Companies Register under number <strong>944 684 778</strong>, 180 B chemin de Saint Andre 13760 Saint-Cannat',
    ml_s1_highlight:  'This website was designed and developed by <strong>Sinda Amara</strong> and <strong>Thomas Palot</strong>, second-year BUT Computer Science students, as part of their internship at POP-E.',
    ml_s1_siege:      'Registered office',
    ml_s1_siege_val:  '180 B CHEMIN DE SAINT ANDRE 13760 SAINT-CANNAT',
    ml_s1_siret:      'SIRET',
    ml_s1_siret_val:  '944 684 778 00001',
    ml_s1_tva:        'VAT no.',
    ml_s1_tva_val:    'FR11 944 684 778',
    ml_s1_dir:        'Publication dir.',
    ml_s1_dir_val:    'Andréa Tatikian',
    ml_s1_dev:        'Developers',
    ml_s1_dev_val:    'Sinda Amara and Thomas Palot — BUT Computer Science interns, 2nd year',
    ml_s1_email:      'Email',

    ml_s2_num:        '02',
    ml_s2_title:      'HOSTING',
    ml_s2_p1:         'The website is hosted by:',
    ml_s2_soc:        'Company',
    ml_s2_soc_val:    '[Hosting provider name]',
    ml_s2_addr:       'Address',
    ml_s2_addr_val:   '[Hosting provider address]',
    ml_s2_site:       'Website',
    ml_s2_site_val:   '[Hosting provider website]',

    ml_s3_num:        '03',
    ml_s3_title:      'INTELLECTUAL PROPERTY',
    ml_s3_p1:         'All elements of this website (texts, graphics, software, photographs, images, sounds, maps, logos, trademarks, etc.) are the exclusive property of <strong>POP-E SAS</strong> or its partners.',
    ml_s3_p2:         'Any reproduction, representation, modification, publication, adaptation or use of all or part of the elements of the website, by any means or process, is prohibited without the prior written authorisation of POP-E SAS.',
    ml_s3_highlight:  'The <strong>POP-E</strong> trademark, logo and associated distinctive signs are registered trademarks. Any unauthorised use constitutes infringement subject to penalties.',

    ml_s4_num:        '04',
    ml_s4_title:      'LIMITATION OF LIABILITY',
    ml_s4_p1:         'POP-E SAS endeavours to ensure the accuracy and currency of information published on this website. However, POP-E SAS cannot guarantee the accuracy, precision or completeness of information made available.',
    ml_s4_p2:         'POP-E SAS accepts no liability for:',
    ml_s4_li1:        'Any imprecision, inaccuracy or omission regarding information available on the website',
    ml_s4_li2:        'Any damage resulting from fraudulent third-party intrusion leading to the modification of information',
    ml_s4_li3:        'Any damage suffered by the user due to an interruption or unavailability of the service',
    ml_s4_li4:        'Any damage caused by hyperlinks and the content of websites to which those links point',

    ml_s5_num:        '05',
    ml_s5_title:      'PERSONAL DATA',
    ml_s5_p1:         'The processing of personal data collected through this website is governed by our <a href="/legal/confidentialite.html">Privacy Policy</a>, in accordance with the General Data Protection Regulation (GDPR — EU 2016/679).',
    ml_s5_p2:         'You have the right to access, rectify, erase and port your data. To exercise these rights, consult the <a href="/legal/confidentialite.html">Privacy Policy</a> page or contact us at <a href="mailto:contact@pop-e.eu">contact@pop-e.eu</a>.',

    ml_s6_num:        '06',
    ml_s6_title:      'COOKIES',
    ml_s6_p1:         'At present, pop-e.fr does not use any non-essential cookies or trackers requiring prior visitor consent. Only technically necessary trackers may be used to ensure page display, website security or navigation. Should audience measurement, advertising or tracking cookies be added in the future, a compliant consent banner will be put in place.',

    ml_s7_num:        '07',
    ml_s7_title:      'APPLICABLE LAW',
    ml_s7_p1:         'These legal notices are governed by French law. In the event of a dispute and in the absence of an amicable settlement, the French courts shall have sole jurisdiction.',
    ml_s7_p2:         'In accordance with Article L.612-1 of the French Consumer Code, any consumer has the right to use a consumer mediator free of charge to resolve disputes with a professional.',

    ml_s8_num:        '08',
    ml_s8_title:      'CONTACT',
    ml_s8_p1:         'For any questions regarding these legal notices, please contact us:',
    ml_s8_email:      'Email',
    ml_s8_courrier:   'Post',
    ml_s8_courrier_val: 'POP-E SAS — 180 B chemin de Saint-André 13760 Saint-Cannat, France',

    /* ── Terms of use ── */
    cgu_badge:        'TERMS OF USE',
    cgu_title:        'GENERAL<br><span>TERMS</span><br>OF USE',
    cgu_meta_date:    'Effective 1 June 2026',
    cgu_meta_version: 'Version 1.0',

    cgu_toc_title:    'CONTENTS',
    cgu_toc_1:        'Purpose and scope',
    cgu_toc_2:        'Service description',
    cgu_toc_3:        'Registration and user account',
    cgu_toc_4:        'Terms of use',
    cgu_toc_5:        'Pricing and payment',
    cgu_toc_6:        'Liability',
    cgu_toc_7:        'Suspension and termination',
    cgu_toc_8:        'Personal data',
    cgu_toc_9:        'Amendments to the terms',
    cgu_toc_10:       'Disputes',
    cgu_toc_11:       'Contact us',

    cgu_s1_num:       '01',
    cgu_s1_title:     'PURPOSE AND SCOPE',
    cgu_s1_p1:        'These General Terms of Use (GTU) govern access to and use of the POP-E service offered by <strong>POP-E SAS</strong>, as well as the associated mobile application and website.',
    cgu_s1_p2:        'By accessing the service, you unconditionally accept these GTU in their entirety. If you do not accept these terms, you must not use the POP-E service.',
    cgu_s1_highlight: 'These GTU apply to any user who has created a POP-E account or used a POP-E external battery rental station.',

    cgu_s2_num:       '02',
    cgu_s2_title:     'SERVICE DESCRIPTION',
    cgu_s2_p1:        'POP-E offers a <strong>self-service external battery rental</strong> accessible through stations installed at partner locations (festivals, shopping centres, transport hubs, etc.).',
    cgu_s2_p2:        'The service includes:',
    cgu_s2_li1:       'Portable external batteries made available via connected stations',
    cgu_s2_li2:       'A mobile app to locate stations, manage rentals and process payment',
    cgu_s2_li3:       'A flexible return system at any station in the POP-E network',
    cgu_s2_li4:       'Real-time rental and billing tracking',
    cgu_s2_p3:        'POP-E reserves the right to modify or discontinue all or part of the service at any time, with or without notice.',

    cgu_s3_num:       '03',
    cgu_s3_title:     'REGISTRATION AND USER ACCOUNT',
    cgu_s3_p1:        'Use of the POP-E service requires the creation of a user account. You agree to:',
    cgu_s3_li1:       'Provide accurate, complete and up-to-date information upon registration',
    cgu_s3_li2:       'Maintain the confidentiality of your login credentials',
    cgu_s3_li3:       'Be solely responsible for all actions taken from your account',
    cgu_s3_li4:       'Notify POP-E immediately of any unauthorised use of your account',
    cgu_s3_p2:        'The service is reserved for adults (18 years and over) or minors with explicit parental consent. POP-E reserves the right to refuse registration or suspend an account without justification.',

    cgu_s4_num:       '04',
    cgu_s4_title:     'TERMS OF USE',
    cgu_s4_p1:        'By using the POP-E service, you agree to:',
    cgu_s4_li1:       'Use the batteries solely to charge personal electronic devices',
    cgu_s4_li2:       'Return the battery to a POP-E station within a maximum of <strong>72 hours</strong>',
    cgu_s4_li3:       'Handle the batteries with care and not intentionally damage them',
    cgu_s4_li4:       'Not attempt to disassemble, modify or tamper with the batteries or stations',
    cgu_s4_li5:       'Not use the service for any unlawful purpose or contrary to public order',
    cgu_s4_highlight: 'In the event of loss or non-return of a battery beyond 72 hours, a flat-rate <strong>replacement fee</strong> will be automatically charged to your registered payment method.',

    cgu_s5_num:       '05',
    cgu_s5_title:     'PRICING AND PAYMENT',
    cgu_s5_p1:        'Current pricing is displayed in the POP-E app and on stations before each rental. Billing is calculated based on the actual rental duration, from the time the battery is taken until it is returned to a station.',
    cgu_s5_th1:       'Duration',
    cgu_s5_th2:       'Price',
    cgu_s5_th3:       'Note',
    cgu_s5_r1c1:      'Up to 30 min',
    cgu_s5_r1c2:      'Free',
    cgu_s5_r1c3:      'Subject to availability',
    cgu_s5_r2c1:      '30 min — 4h',
    cgu_s5_r2c2:      'From €1.50',
    cgu_s5_r2c3:      'Per 30-minute increment',
    cgu_s5_r3c1:      '4h — 24h',
    cgu_s5_r3c2:      'From €5',
    cgu_s5_r3c3:      'Daily rate',
    cgu_s5_r4c1:      'Beyond 72h',
    cgu_s5_r4c2:      'Replacement fee',
    cgu_s5_r4c3:      'Rate shown in the app',
    cgu_s5_p2:        'Payment is accepted exclusively by credit/debit card or via payment solutions integrated into the app (Apple Pay, Google Pay). Cash payments are not accepted.',

    cgu_s6_num:       '06',
    cgu_s6_title:     'LIABILITY',
    cgu_s6_p1:        'POP-E is committed to using all reasonable means to ensure the availability and proper functioning of the service. However, POP-E cannot be held liable for:',
    cgu_s6_li1:       'Damage caused to your devices through the use of the batteries',
    cgu_s6_li2:       'Service interruptions due to maintenance or technical failures',
    cgu_s6_li3:       'Acts of vandalism or theft at stations beyond its control',
    cgu_s6_li4:       'Loss of data or information stored on your devices',
    cgu_s6_p2:        'As a user, you are entirely responsible for your use of the service and the consequences thereof.',

    cgu_s7_num:       '07',
    cgu_s7_title:     'SUSPENSION AND TERMINATION',
    cgu_s7_p1:        'POP-E reserves the right to suspend or terminate your account in the event of:',
    cgu_s7_li1:       'Breach of these terms',
    cgu_s7_li2:       'Fraudulent behaviour or attempted fraud',
    cgu_s7_li3:       'Non-payment of amounts owed',
    cgu_s7_li4:       'Non-return of equipment after formal notice',
    cgu_s7_p2:        'You may request deletion of your account at any time by contacting our customer service or via the app settings.',

    cgu_s8_num:       '08',
    cgu_s8_title:     'PERSONAL DATA',
    cgu_s8_p1:        'POP-E collects and processes your personal data in order to provide the service, in accordance with the GDPR. For more information, see our <a href="/legal/confidentialite.html">Privacy Policy</a>.',

    cgu_s9_num:       '09',
    cgu_s9_title:     'AMENDMENTS TO THE TERMS',
    cgu_s9_p1:        'POP-E reserves the right to amend these terms at any time. Amendments take effect upon publication on the website and app. In the event of a material change, you will be notified by email at least 15 days before it takes effect.',
    cgu_s9_p2:        'Continued use of the service after notification constitutes acceptance of the new terms.',

    cgu_s10_num:      '10',
    cgu_s10_title:    'DISPUTES',
    cgu_s10_p1:       'In the event of a dispute, you may contact our customer service for an amicable resolution. If no agreement is reached, you may refer the matter to a consumer mediator free of charge.',
    cgu_s10_p2:       'These terms are governed by French law. In the absence of an amicable settlement, the competent courts of Paris shall have jurisdiction.',

    cgu_s11_num:      '11',
    cgu_s11_title:    'CONTACT US',
    cgu_s11_p1:       'For any questions regarding these terms, a complaint or a request for account deletion, please contact us via the form below.',
    cgu_form_fname:   'First name *',
    cgu_form_lname:   'Last name *',
    cgu_form_email:   'Email *',
    cgu_form_phone:   'Phone (optional)',
    cgu_form_subject: 'Subject of your request *',
    cgu_form_opt1:    'Question about the terms',
    cgu_form_opt2:    'Complaint',
    cgu_form_opt3:    'Account deletion',
    cgu_form_opt4:    'Payment dispute',
    cgu_form_opt5:    'Other',
    cgu_form_msg:     'Your message *',
    cgu_form_submit:  'SEND MY MESSAGE →',
    cgu_form_sending: 'SENDING...',
    cgu_form_error:   'ERROR — RETRY',
    cgu_form_success: '✓ Your message has been sent. We will reply within 48 hours.',

    /* ── Privacy policy ── */
    conf_badge:       'GDPR — EU 2016/679',
    conf_title:       'PRIVACY<br><span>POLICY</span>',
    conf_meta_date:   'Updated: June 2026',
    conf_meta_rgpd:   'GDPR Compliant',

    conf_toc_title:   'CONTENTS',
    conf_toc_1:       'Data controller',
    conf_toc_2:       'Data collected',
    conf_toc_3:       'Purposes and legal bases',
    conf_toc_4:       'Retention periods',
    conf_toc_5:       'Data sharing',
    conf_toc_6:       'Transfers outside the EU',
    conf_toc_7:       'Security',
    conf_toc_8:       'Your rights',
    conf_toc_9:       'Cookies',
    conf_toc_10:      'Exercise your rights',

    conf_intro:       'POP-E is committed to protecting your privacy. This policy explains what data we collect, why, how we use it and what your rights are. We never sell your personal data to third parties.',

    conf_s1_num:      '01',
    conf_s1_title:    'DATA CONTROLLER',
    conf_s1_p1:       'The controller responsible for processing your personal data is:',
    conf_s1_soc:      'Company',
    conf_s1_addr:     'Address',
    conf_s1_addr_val: '180 B CHEMIN DE SAINT ANDRE, 13760 Saint-Cannat, France',
    conf_s1_dpo:      'DPO / Contact',

    conf_s2_num:      '02',
    conf_s2_title:    'DATA COLLECTED',
    conf_s2_p1:       'We collect the following categories of data depending on your use of the service:',
    conf_s2_th1:      'Category',
    conf_s2_th2:      'Data collected',
    conf_s2_th3:      'Source',
    conf_s2_r1c1:     'Identity',
    conf_s2_r1c2:     'Last name, first name, date of birth',
    conf_s2_r1c3:     'Direct registration',
    conf_s2_r2c1:     'Contact',
    conf_s2_r2c2:     'Email address, phone number',
    conf_s2_r2c3:     'Direct registration',
    conf_s2_r3c1:     'Payment',
    conf_s2_r3c2:     'Tokenised bank data (via PSP provider)',
    conf_s2_r3c3:     'At payment',
    conf_s2_r4c1:     'Location',
    conf_s2_r4c2:     'GPS position (only if authorised)',
    conf_s2_r4c3:     'Mobile app',
    conf_s2_r5c1:     'Usage',
    conf_s2_r5c2:     'Rental history, stations used, durations',
    conf_s2_r5c3:     'Service use',
    conf_s2_r6c1:     'Technical',
    conf_s2_r6c2:     'IP address, device type, operating system',
    conf_s2_r6c3:     'Automatic browsing',
    conf_s2_p2:       'We do not collect sensitive data within the meaning of Article 9 of the GDPR (ethnic origin, health data, political opinions, etc.).',

    conf_s3_num:      '03',
    conf_s3_title:    'PURPOSES AND LEGAL BASES',
    conf_s3_th1:      'Purpose',
    conf_s3_th2:      'Legal basis',
    conf_s3_r1c1:     'Account management and service provision',
    conf_s3_r1c2:     'Contract performance',
    conf_s3_r2c1:     'Billing and payment management',
    conf_s3_r2c2:     'Contract performance / Legal obligation',
    conf_s3_r3c1:     'Sending rental-related notifications',
    conf_s3_r3c2:     'Contract performance',
    conf_s3_r4c1:     'Commercial communications and POP-E offers',
    conf_s3_r4c2:     'Consent (opt-in)',
    conf_s3_r5c1:     'Service improvement and audience analysis',
    conf_s3_r5c2:     'Legitimate interest',
    conf_s3_r6c1:     'Fraud prevention and security',
    conf_s3_r6c2:     'Legitimate interest / Legal obligation',
    conf_s3_r7c1:     'Compliance with legal and accounting obligations',
    conf_s3_r7c2:     'Legal obligation',

    conf_s4_num:      '04',
    conf_s4_title:    'RETENTION PERIODS',
    conf_s4_li1:      '<strong>Active account data</strong> — retained for the duration of the contractual relationship',
    conf_s4_li2:      '<strong>Transaction data</strong> — 10 years (accounting obligation)',
    conf_s4_li3:      '<strong>Rental history</strong> — 3 years after last use',
    conf_s4_li4:      '<strong>Connection data / logs</strong> — 12 months',
    conf_s4_li5:      '<strong>Location data</strong> — 90 days',
    conf_s4_li6:      '<strong>Marketing data (if consent given)</strong> — until consent is withdrawn or 3 years of inactivity',
    conf_s4_p1:       'After these periods expire, your data is either deleted or irreversibly anonymised for statistical purposes.',

    conf_s5_num:      '05',
    conf_s5_title:    'DATA SHARING',
    conf_s5_p1:       'Your data may be shared with the following categories of recipients, strictly within the scope of the purposes described:',
    conf_s5_li1:      '<strong>Payment providers</strong> — for secure transaction processing (e.g. Stripe, Mangopay)',
    conf_s5_li2:      '<strong>Hosting providers and technical partners</strong> — for service operation',
    conf_s5_li3:      '<strong>Analytics providers</strong> — for service improvement (anonymised data or under GDPR sub-processing agreement)',
    conf_s5_li4:      '<strong>Competent authorities</strong> — only upon judicial or legal request',
    conf_s5_highlight: '<strong>We never sell your personal data</strong> to third parties for commercial purposes.',

    conf_s6_num:      '06',
    conf_s6_title:    'TRANSFERS OUTSIDE THE EU',
    conf_s6_p1:       'Some of our technical providers may be established outside the European Union. In such cases, we ensure that data transfers are governed by appropriate safeguards:',
    conf_s6_li1:      'Adequacy decision by the European Commission',
    conf_s6_li2:      'Standard Contractual Clauses (SCCs) approved by the European Commission',
    conf_s6_li3:      'Provider certification under a recognised mechanism (e.g. EU-US Data Privacy Framework)',

    conf_s7_num:      '07',
    conf_s7_title:    'SECURITY',
    conf_s7_p1:       'POP-E implements appropriate technical and organisational measures to protect your data against unauthorised access, disclosure, alteration or destruction:',
    conf_s7_li1:      'Data encrypted in transit (TLS 1.3) and at rest (AES-256)',
    conf_s7_li2:      'Data access limited to authorised personnel only',
    conf_s7_li3:      'Two-factor authentication for administrator access',
    conf_s7_li4:      'Regular security audits',
    conf_s7_li5:      'Data breach notification procedure within 72 hours (GDPR art. 33)',

    conf_s8_num:      '08',
    conf_s8_title:    'YOUR RIGHTS',
    conf_s8_p1:       'Under the GDPR, you have the following rights regarding your personal data:',
    conf_s8_th1:      'Right',
    conf_s8_th2:      'Description',
    conf_s8_r1c1:     'Access',
    conf_s8_r1c2:     'Obtain a copy of all your personal data we process',
    conf_s8_r2c1:     'Rectification',
    conf_s8_r2c2:     'Correct inaccurate or incomplete data about you',
    conf_s8_r3c1:     'Erasure',
    conf_s8_r3c2:     'Request deletion of your data (subject to legal obligations)',
    conf_s8_r4c1:     'Restriction',
    conf_s8_r4c2:     'Restrict the processing of your data in certain circumstances',
    conf_s8_r5c1:     'Portability',
    conf_s8_r5c2:     'Receive your data in a structured, machine-readable format',
    conf_s8_r6c1:     'Objection',
    conf_s8_r6c2:     'Object to processing based on legitimate interest or for marketing purposes',
    conf_s8_r7c1:     'Withdrawal of consent',
    conf_s8_r7c2:     'Withdraw your consent at any time without affecting prior processing',
    conf_s8_p2:       'You also have the right to lodge a complaint with the <strong>CNIL</strong> (French data protection authority): <a href="https://www.cnil.fr" target="_blank" rel="noopener">www.cnil.fr</a>',

    conf_s9_num:      '09',
    conf_s9_title:    'COOKIES',
    conf_s9_p1:       'Our website uses cookies and similar technologies. You can manage your preferences at any time via our consent banner or your browser settings.',
    conf_s9_th1:      'Type',
    conf_s9_th2:      'Purpose',
    conf_s9_th3:      'Duration',
    conf_s9_th4:      'Consent',
    conf_s9_r1c1:     'Essential',
    conf_s9_r1c2:     'Site functionality, session, language',
    conf_s9_r1c3:     'Session',
    conf_s9_r1c4:     'Not required',
    conf_s9_r2c1:     'Analytics',
    conf_s9_r2c2:     'Anonymised audience measurement',
    conf_s9_r2c3:     '13 months',
    conf_s9_r2c4:     'Required',
    conf_s9_r3c1:     'Functional',
    conf_s9_r3c2:     'User preference storage',
    conf_s9_r3c3:     '12 months',
    conf_s9_r3c4:     'Required',
    conf_s9_r4c1:     'Marketing',
    conf_s9_r4c2:     'Personalised advertising (if enabled)',
    conf_s9_r4c3:     '6 months',
    conf_s9_r4c4:     'Required',

    conf_s10_num:     '10',
    conf_s10_title:   'EXERCISE YOUR RIGHTS',
    conf_s10_p1:      'To exercise any of your rights, fill in the form below. We commit to responding within <strong>one month</strong> of receiving your request (GDPR art. 12).',
    conf_s10_p2:      'Proof of identity may be requested to verify your identity before processing.',
    conf_form_fname:  'First name *',
    conf_form_lname:  'Last name *',
    conf_form_email:  'Email linked to your POP-E account *',
    conf_form_phone:  'Phone (optional)',
    conf_form_right:  'Right you wish to exercise *',
    conf_form_opt1:   'Right of access — obtain my data',
    conf_form_opt2:   'Right of rectification — correct my data',
    conf_form_opt3:   'Right of erasure — delete my data',
    conf_form_opt4:   'Right to restriction of processing',
    conf_form_opt5:   'Right to data portability',
    conf_form_opt6:   'Right to object',
    conf_form_opt7:   'Withdrawal of marketing consent',
    conf_form_opt8:   'Other request',
    conf_form_detail: 'Additional details (optional)',
    conf_form_submit: 'SUBMIT MY REQUEST →',
    conf_form_sending:'SENDING...',
    conf_form_error:  'ERROR — RETRY',
    conf_form_success:'✓ Your request has been received. We will respond within one month.',

    /* ── Footer ── */
    footer_tagline:   'The self-service external battery.<br>Everywhere. All the time.',
    footer_col1:      'Solution',
    footer_how:       'How it works',
    footer_where:     'Where to use POP-E',
    footer_amb:       'Ambassador',
    footer_col2:      'Company',
    footer_about:     'About us',
    footer_impact:    'Impact',
    footer_press:     'Press',
    footer_col3:      'Contact',
    footer_contact:   'Contact us',
    footer_install:   'Install a station',
    footer_support:   'Support',
    footer_rights:    '© 2026 POP-E. All rights reserved.',
    footer_legal1:    'Legal notice',
    footer_cgu:       'Terms of use',
    footer_privacy:   'Privacy',
  }
};

const LANG_META = {
  fr: { flag: '🇫🇷', code: 'FR' },
  en: { flag: '🇬🇧', code: 'EN' },
};

let currentLang = localStorage.getItem('pope-lang') || 'fr';

function applyLegalLang(lang) {
  const t = LEGAL_TRANSLATIONS[lang];
  if (!t) return;

  document.querySelectorAll('[data-i18n]').forEach(el => {
    const key = el.dataset.i18n;
    if (t[key] !== undefined) el.innerHTML = t[key];
  });

  document.querySelectorAll('[data-i18n-placeholder]').forEach(el => {
    const key = el.dataset.i18nPlaceholder;
    if (t[key]) el.placeholder = t[key];
  });

  document.documentElement.lang = lang;

  const meta = LANG_META[lang];
  const flagEl = document.getElementById('lang-flag');
  const codeEl = document.getElementById('lang-code');
  if (flagEl) flagEl.textContent = meta.flag;
  if (codeEl) codeEl.textContent = meta.code;

  currentLang = lang;
  localStorage.setItem('pope-lang', lang);
}

(function () {
  const btn      = document.getElementById('lang-btn');
  const dropdown = document.getElementById('lang-dropdown');
  if (!btn || !dropdown) return;

  function updateDropdown() {
    dropdown.querySelectorAll('.lang-option').forEach(opt => {
      opt.style.display = opt.dataset.lang === currentLang ? 'none' : 'flex';
    });
  }

  btn.addEventListener('click', (e) => {
    e.stopPropagation();
    const isOpen = dropdown.classList.contains('visible');
    updateDropdown();
    dropdown.classList.toggle('visible', !isOpen);
    btn.classList.toggle('open', !isOpen);
    btn.setAttribute('aria-expanded', String(!isOpen));
  });

  dropdown.querySelectorAll('.lang-option').forEach(opt => {
    opt.addEventListener('click', () => {
      applyLegalLang(opt.dataset.lang);
      updateDropdown();
      dropdown.classList.remove('visible');
      btn.classList.remove('open');
      btn.setAttribute('aria-expanded', 'false');
    });
  });

  document.addEventListener('click', (e) => {
    if (!btn.contains(e.target) && !dropdown.contains(e.target)) {
      dropdown.classList.remove('visible');
      btn.classList.remove('open');
      btn.setAttribute('aria-expanded', 'false');
    }
  });

  document.addEventListener('keydown', (e) => {
    if (e.key === 'Escape') {
      dropdown.classList.remove('visible');
      btn.classList.remove('open');
      btn.setAttribute('aria-expanded', 'false');
    }
  });

  applyLegalLang(currentLang);
  updateDropdown();
})();